# Code Generated by ZenTest v. 4.10.0
#                 classname: asrt / meth =  ratio%
#                   Numeric:    0 /    2 =   0.00%

require_relative 'test_helper'
require "rrobots/numeric"

class TestNumeric < Minitest::Test
  def test_to_deg
    assert_in_epsilon   0, (0.0*Math::PI).to_deg
    assert_in_epsilon  90, (0.5*Math::PI).to_deg
    assert_in_epsilon 180, (1.0*Math::PI).to_deg
    assert_in_epsilon 270, (1.5*Math::PI).to_deg
    assert_in_epsilon 360, (2.0*Math::PI).to_deg
  end

  def test_to_rad
    assert_in_epsilon (0.0*Math::PI),   0.to_rad
    assert_in_epsilon (0.5*Math::PI),  90.to_rad
    assert_in_epsilon (1.0*Math::PI), 180.to_rad
    assert_in_epsilon (1.5*Math::PI), 270.to_rad
    assert_in_epsilon (2.0*Math::PI), 360.to_rad
  end
end

# Number of errors detected: 42
